### ISSUE TITLE
Why use apollo-server-lambda and not graphql-js?

### ISSUE THREAD

**Issue by ibilux** [vibhanshu909/graphql-server#3]
Hello,
I'm new to graphql, so I have a lot of question, and I hope you may answer them.
1- why do you use apollo-server-lambda and not graphql-js directly?
2- does apollo-server-lambda with sveltekit support Subscription ? the reason  I'm interested in graphql is mainly the Subscription.

**Comment by vibhanshu909** [comment]
Hey, @ibilux this package only allows you to set up the server-side of graphql not the client-side.

1) I used apollo-server-lambda because it comes with all the code you need to create and set up a graphql server, so why reinvent the wheel with graphql-js.

2) I don't think so, because Sveltekit can be deployed to a Server and Serverless environment, and subscription can't function in a serverless environment.
